[[gnosoft-prematriculas]]

////
a=&#225; e=&#233; i=&#237; o=&#243; u=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== PREMATRICULAS

. *RECURSOS:*

* FORMATO DE PREMATRICULA - Formato por defecto de GNOSOFT

. *ACTIVIDADES A REALIZAR:*

1. HABILITAR EL A&#209;O ELECTIVO

* [Acad&#233;mico administrador][Estructura curricular][Gestionar A&#241;o electivo] -> Se define el a&#241;o y la fecha.

1. HABILITAR LAS FECHAS DE LA PREMATRICULA

* [Acad&#233;mico administrador][Matr&#237;cula][Gestionar fecha de Prematr&#237;cula] -> Se define el a&#241;o y la fecha.

1. HABILITAR LA OPCION A ROL

* [General][Asignar Funcionalidades a Rol][ACUDIENTE o ACUDIENTE MOROSO][Acad&#233;mico acudiente][Prematricular estudiante]

4. REALIZAR LA PREMATRICULA

* [Acad&#233;mico administrador][Matr&#237;cula][Prematricular el estudiante] --- Por Acad&#233;mico administrador
* [Acad&#233;mico acudiente] [Prematricular el Estudiante] --- Por Acad&#233;mico acudiente.

1. LISTADOS DE PREMATRICULAS

* [Acad&#233;mico administrador][Consultas y reportes][Generar reportes][MATRICULA][Listado Estudiantes seg&#250;n prematr&#237;cula]
* [Acad&#233;mico administrador][Consultas y reportes][Generar reportes][MATRICULA][Listado de estudiantes sin prematricula]
* [Acad&#233;mico administrador][Consultas y reportes][Consolidados][Consolidado de prematricula]
* [Acad&#233;mico administrador][Consultas y reportes][Generar reportes][ESTUDIANTE][Cuentas de Usuario Estudiantes y Acudientes] - Se debe generar para nuevos y antiguos

1. BLOQUEAR PREMATRICULA DEL ESTUDIANTE

* [Acad&#233;mico administrador][Matr&#237;cula][Bloquear Prematricula Estudiante] -- Se debe seleccionar el a&#241;o electivo actual

. AVISO PARA EL INFORMATIVO

::
Se&#241;ores Padres de Familia para comunicarles que a partir del lunes 20 de octubre hasta el 31 de octubre,
ser&#225; habilitado el sistema para realizar las PRE Matr&#237;cula a&#241;o 2015.


1. *CORREO PARA ADMISIONES Y MATRICULAS*

::
Correo para los padres enviado por Gnosoft por el usuario de Admisiones y Matriculas:


----
 ASUNTO: PASOS PARA REALIZAR LA PREMATRICULA

 Cordial Saludo,

 Para el proceso de PreMatricula se deben tener presente los siguientes pasos:

 PASOS:

 1. Ingresar a Gnosoft
 2. Selecionar la opcio: [Academico acudiente][Prematricular Estudiante]
 3. Realizar la prematricula de cada uno de sus hijos:
 4. Seleccionar SI/NO para realizar la prematricula
 5. Actualizar los datos personales
 6. Presionar [Registrar] para grabar la prematr&#237;cula
 7. El sistema genera el formulario para separaci&#243;n de cupo del a&#241;o electivo.
----


1. *PREMATRICULA POR LA OPCION DEL ADMINISTRADOR*

----
Ingresar a Gnosoft

Selecionar la opciOn: [Academico administrador][Matricula][Prematricular el estudiante]

Buscar el estudiante a Prematicular

Realizar la prematricula del estudiante.
----

1. *BLOQUEAR PREMATRICULA DEL ESTUDIANTE*

.. Ingresar a Gnosoft
.. Selecionar la opci&#243;n: [Acad&#233;mico administrador][Matr&#237;cula][Bloquear Prematricula Estudiante]
.. Selecionar el a&#241;o electivo actual.
.. Selecionar el el grado y curso
.. Selecionar los estudiantes a los cuales se va a bloquear la Prematricula.
.. Selecionar [Registrar] para grabar los cambios.

1. *INFORMES DE LAS PREMATRICULAS*

* [Acad&#233;mico administrador][Consultas y reportes][Generar reportes][MATRICULA][Listado Estudiantes seg&#250;n prematr&#237;cula]

* [Acad&#233;mico administrador][Consultas y reportes][Generar reportes][MATRICULA][Listado de estudiantes sin prematricula]

* [Acad&#233;mico administrador][Consultas y reportes][Consolidados][Consolidado de prematricula]