[[simadata-configuracion]]

////
a=&#225; e=&#233; i=&#237; o=&#243; u=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== SIMADATA

=== [[CONFIGURACIONES PARA GENERAR EL REPORTE DE DATACREDITO]]CONFIGURACIONES PARA GENERAR EL REPORTE DE DATACREDITO

==== CONFIGURACIONES EN SIMADATA:

* [UTILIDADES][CONFIGURACION][CONFIGURACION GENERAL]

** *CODIGO DE LA EMPRESA* = C&#243;digo Interno asociado al Colegio.

** *NOMBRE DE LA EMPRESA* = Nombre del Colegio = 2.44 OFICINA DE RADICACION

** *CIUDAD DE LA EMPRESA* =  Ciudad del Colegio =  2.45 CIUDAD DE RADICACION

* [UTILIDADES][CONFIGURACION][CONFIGURACION SISTEMA]

** *CLASE DE REPORTE* = Se debe asignar el n&#250;mero 1

** *CAMPO 1.2 CODIGO DEL SUSCRIPTOR* =  El c&#243;digo asignado al Colegio por DataCr&#233;dito

** *CAMPO 1.3 TIPO DE CUENTA* = 43 : Cartera Educaci&#243;n. Anexo No. 2.1

** *CAMPO 2.9 TIPO OBLIGACION* = 4 :  Otro. Anexo No. 2.3

** *CAMPO 2.14 PERIOCIDAD DE PAGO* = 1 : Mensual

** *CAMPO 2.27 TIPO MONEDA* = 1 : Legal

** *CAMPO 2.28 TIPO GARANTIA* = 1 : Admisible

* [UTILIDADES][CONFIGURACION][CONFIGURACION A&#209;O]

** *TOTAL COUTAS* = Se debe definir el total de cuotas. Corresponde al n&#250;mero total de cuotas para cancelar la totalidad de la obligaci&#243;n.

** *CONTRATANTES A REPORTAR:* Definir el numero de contratantes a reportar.

*** Una vez se haya definido el n&#250;mero de contratantes a reportar se debe tener presente que la variaci&#243;n debe ser de menor a mayor y no de mayor a menor.

*** El sistema reporta el total de contratantes en orden secuencial desde el primer contratante sin tener en cuenta los contratantes no definidos.

** *TIPO DE REPORTE* = Se debe definir el tipo de reporte. Los tipos de reportes son:

*** 1 => El sistema de acuerdo al n&#250;mero de contratantes a reportar TIENE EN CUENTA los contratantes no definidos, es decir lo cuenta, mas no lo reporta.

*** 2 => El sistema de acuerdo al n&#250;mero de contratantes a reportar NO TIENE EN CUENTA los contratantes no definidos, es decir NO lo suma y busca el siguiente contratante para reportarlo.

** *VALIDAR CONTRATANTES:* Se debe definir el tipo de validaci&#243;n. Los tipos de validaci&#243;n son los siguientes:

*** 1 al 4 = Valida la existencia de TODOS los contratantes en su orden secuencial, y verifica que todos los contratantes est&#233;n definidos

*** 9 = No realiza ning&#250;n tipo de validaci&#243;n de los contratantes, permite que existan estudiantes sin ning&#250;n contratante definido y no lo tiene en cuenta para el reporte.

** *VALIDAR REPORTE:* Campo Reservado para uso del sistema

** *MESES DE PLAZO:* Son los meses de plazo que se establecen para generar el reporte.

*** Para activar la modificacion del campo: [UTILIDADES][CONFIGURACION][CONFIGURACION SISTEMA] HABILITAR MODIFICACION

* [UTILIDADES][MANTENIMIENTO][EMPRESAS]

** En esta opci&#243;n se registran todos los Colegios para que el sistema genere un solo archivo para DATACREDITO.
   Si se va a genera localmente en cada colegio solo se debe registra un solo registro con el c&#243;digo y nombre del Colegio.

** *CODIGO EMPRESA:* C&#243;digo Interno asociado al Colegio.

** *NOMBRE DE EMPRESA:* Nombre del Colegio

* [UTILIDADES][MANTENIMIENTO][VALOR INICIAL]

** Para cada grado de estudio se debe definir el valor inicial de la obligaci&#243;n que corresponde al total mensual de los costos 
   educativos que se facturan en el recibo de la pensi&#243;n.

** Es importante resaltar que el sistema utiliza este total para calcular el valor del mes que se factura y asi 
   calcular los meses pagados o en mora, y tambi&#233;n sirve de base para calcular el tipo de novedad que se va a reportar.

** Una gu&#237;a es observar las cifras de cualquier a&#241;o anterior para que sirva de base de como se deben definir las del a&#241;o actual.

==== CONFIGURACIONES EN SIMACART:

* [UTILIDADES][CONFIGURACION][CONFIGURACION SISTEMA]

** *A&#209;O INICIAL PARA REPORTAR* = Se debe definir el a&#241;o inicial a reportar

** *A&#209;O FINAL PARA REPORTAR* = Se debe definir el a&#241;o inicial a reportar

* [UTILIDADES][CONFIGURACION][CONFIGURACION DEL A&#209;O]

** *MES INICIAL DE FACTURACION* = Se debe definir el primer mes de la facturaci&#243;n. En la mayoria de los casos 2 del mes de Febrero

** *MES FINAL DE FACTURACION* = Se debe definir el &#250;ltimo mes de facturaci&#243;n
