[[simacart-dian]]

////
a=&#225; e=&#233; i=&#237; o=&#243; u=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== REPORTE DE LA DIAN

PARA CADA AÑO QUE SE VAYA INCLUIR EN EL REPORTE SE DEBEN SEGUIR LOS SIGUIENTES PASOS:

GENERAR EL ARCHIVO CON EL TOTAL DE LO FACTURADO Y PAGADO DEL AÑO A REPORTAR:
[INFORMES][FACTURACION Y PAGOS]
FECHA DE CORTE: DIC 31 DEL AÑO DEL REPORTE
SELECCION DEL TIPO DE IMPRESION: [En Archivo][A Formato Dbf]
Nombre del archivo: TotpAAAA. Por defecto el nombre del archivo TotPagos.dbf
Reportar a: 1<CONTRATANTE>

EL ARCHIVO SE ALMACENA EN EL DIRECTORIO PRINTER. SE INGRESA A EXCEL Y SE ABRE ESTE ARCHIVO Y SE HACEN LAS MODIFICACIONES Y FILTROS NECESARIOS.
PARA ANEXAR LOS CONCEPTOS DE VARIOS SERVICIOS REVISAR EL SIMATOOL.

PARA GENERAR EL ARCHIVO NO SE GRABAN CONCEPTOS DE MATRICULAS

PARA CLASIFICAR LOS CONCEPTOS SI SE GRABA LOS CONCEPTOS DE MATRICULAS

=== CAMPOS DEL ARCHIVO DE EXCEL

CAMPOS DEL ARCHIVO TOTPAGOS
CAMPO1   = SECUENCIAL
CAMPO2   = CODIGO DEL ESTUDIANTE
CAMPO3   = GRUPO
CAMPO4   = DOCUMENTO
CAMPO5   = APELLIDO1
CAMPO6   = APELLIDO2
CAMPO7   = NOMBRE1
CAMPO8   = NOMBRE2
CAMPO9   = DIRECCION
CAMPO10 = CIUDAD
CAMPO11 = DEPARTAMENTO
CAMPO12 = PAIS - EN LA HOJA DE EXCEL SE DEBE REEMPLAZAR POR COLOMBIA
CAMPO13 = TOTAL FACTURADO O PAGADO
CAMPO14 = SALDO DE LA DEUDA
CAMPO15 = TOTAL FACTURADO
CAMPO16 = TOTAL PAGADO


------------------------



DIAN

- CASOS

- DIAN ESTANDAR

** TOTALIZACION DE LA FACTURACION DE LOS N SERVICIOS

** TOTALIZACION DE LOS PAGOS DE LOS N SERVICIOS

** SIMATOOL PARA TOTALIZAR POR CONTRATANTE

- DIAN DISCRIMINADO

** DIAN ESTANDAR

** DISCRIMINACION POR CONCEPTOS

CONFIGURACION DEL AÑO

MATRICULAS CONCEPTOS CERTIFICADOS

CUADROS LEON LIDA - 10C,5A,4A

REPORTES DE LA DIAN

27 de febrero de 2014, 17:05 - Información medios magnéticos 2013 https://mail.google.com/mail/u/0/#apps/cartera%40lasalle.org.co/14475618e9a1f2bf[gi@lasallebga.edu.co]
