[[simacart-siigo]]

////
a=&#225; e=&#233; i=&#237; o=&#243; u=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== SIIGO

=== REQUERIMIENTOS

* Sacar una copia seguridad antes de la actualizaci&#243;n y guardarla para verificar informes para evitar cambios.

* Actualizar el PLUSCART a la versi&#243;n: XML214-02 en adelante.

* Actualizar los extractos de todos los a&#241;os.

* Actualizar los conceptos de las transaciones.

** Configurar el a&#241;o del concepto del mes actual

** Configurar el a&#241;o del concepto otros meses a&#241;o actual

** Configurar el a&#241;o del concepto abono mes actual

** Configurar el a&#241;o de los conceptos de los abonos.

* Imprimir todos los extractos y verificar los a&#241;os asignados a los conceptos de abonos, pensiones.

* Cambiar el conceptos de abonos anteriores para que no lleve el a&#241;o el sistema lo asigna. - Pendiente modificaci&#243;n.

* Cambiar el c&#243;digo del concepto para las pensiones y abonos correspondiente a a&#241;os direferentes al a&#241;o actual

* REPL ALL nCodigoCmv WITH XX FOR nCodigoCmv = XX .and. SUBS(cCodRefTra,7,2) == 'XX'
