[[horizonte]]

////
a=&#225; e=&#233; i=&#237; o=&#243; u=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== HORIZONTE INSTITUCIONAL

=== MISI&#211;N:

La congregaci&#243;n de los Hermanos de las Escuelas Cristianas del Distrito Lasallista de Bogot&#225; y sus colaboradores, orientados por la Iglesia
Cat&#243;lica y los principios de su santo fundador Juan Bautista de la Salle, son una comunidad cuyo carisma *se centra en procurar a la ni&#241;ez y
la juventud una educaci&#243;n humana, cristiana y acad&#233;mica de calidad, con especial atenci&#243;n a los pobres, promoviendo su desarrollo integral.*

=== VISI&#211;N:

En el a&#241;o *2015* la Congregaci&#243;n de los Hermanos de las Escuelas Cristianas del Distrito Lasallista de Bogot&#225;,
*continuar&#225; siendo una comunidad l&#237;der en la prestaci&#243;n del servicio educativo*, que fomenta y vivencia la cultura de la calidad, a trav&#233;s
de una formaci&#243;n integral y en concordancia con las exigencias de la normatividad vigente.

=== POLITICA DE CALIDAD:

El servicio educativo que ofrece la Congregaci&#243;n de los Hermanos de las Escuelas Cristianas del Distrito Lasallista de Bogot&#225;,
satisface las necesidades y requerimientos de los Estudiantes y Padres de Familia  o Acudientes mediante:

* La Educaci&#243;n humana, cristiana y acad&#233;mica de calidad

* La implementaci&#243;n de un sistema de gesti&#243;n de la calidad que asegure la mejora continua  del servicio educativo.

* La conformaci&#243;n de un Equipo Humano competente

=== OBJETIVOS DE LA CALIDAD:

* Responder a las necesidades y expectativas de los estudiantes en la formaci&#243;n humana, cristiana y acad&#233;mica de acuerdo con la misi&#243;n institucional.

* Garantizar la conformidad del Sistema de Gesti&#243;n de la Calidad con los requisitos legales y de la norma.

* Mejorar continuamente los est&#225;ndares de competencia del talento humano.

=== ALCANCE DEL SGC:

Seg&#250;n el Manual de la Calidad, el sistema de Gesti&#243;n de la Calidad tiene como *alcance* en cada Instituci&#243;n Educativa del Distrito
Lasallista de Bogot&#225;, *el dise&#241;o y la prestaci&#243;n del Servicio Educativo de car&#225;cter formal en los niveles de Preescolar,
Educiaci&#243;n B&#225;sica y Media.* Comprende todos los procesos relacionados en el Mapa de Procesos del SGC de la Congregaci&#243;n de los
Hermanos de las Esculas Cristianas del Distrito Lasallista de Bogot&#225;.